/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AddBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBook
     */
    Connection con = null;
    PreparedStatement pat;
    ResultSet rst;

    public AddBook() {
        initComponents();
        con = DBConnect.connect();
        autoId();
        tablellord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblbookheadibg = new javax.swing.JPanel();
        lblbookmhd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnupbook = new javax.swing.JButton();
        btndltbook = new javax.swing.JButton();
        btnaddbook = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbname = new javax.swing.JTextField();
        txtbid = new javax.swing.JTextField();
        txtedtn = new javax.swing.JTextField();
        txtctgry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetail = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtpage = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtbooktype = new javax.swing.JComboBox<>();
        txtbdate = new com.toedter.calendar.JDateChooser();
        lblmother = new javax.swing.JLabel();
        txtpublisher = new javax.swing.JTextField();
        lblfather = new javax.swing.JLabel();
        txtauthor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTableDetail = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1124, 653));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblbookheadibg.setBackground(new java.awt.Color(153, 204, 255));
        lblbookheadibg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblbookmhd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblbookmhd.setText("Books Manage");

        javax.swing.GroupLayout lblbookheadibgLayout = new javax.swing.GroupLayout(lblbookheadibg);
        lblbookheadibg.setLayout(lblbookheadibgLayout);
        lblbookheadibgLayout.setHorizontalGroup(
            lblbookheadibgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblbookheadibgLayout.createSequentialGroup()
                .addComponent(lblbookmhd, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lblbookheadibgLayout.setVerticalGroup(
            lblbookheadibgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblbookheadibgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblbookmhd)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnupbook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update-32.png"))); // NOI18N
        btnupbook.setText("Update Book");
        btnupbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupbookActionPerformed(evt);
            }
        });

        btndltbook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndltbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-32.png"))); // NOI18N
        btndltbook.setText("Delete Book");
        btndltbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndltbookActionPerformed(evt);
            }
        });

        btnaddbook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-32.png"))); // NOI18N
        btnaddbook.setText("Add Book");
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndltbook, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(btnupbook, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(btnaddbook, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnaddbook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnupbook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btndltbook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        lblid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblid.setText("Book ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Edition");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Date");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Category");

        txtbname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtbid.setEditable(false);
        txtbid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtedtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtctgry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtctgry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select  Category", "Computer Science", "History", "Science", "Language", "Business", "Other" }));
        txtctgry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtctgryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Details");

        txtdetail.setColumns(20);
        txtdetail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtdetail.setRows(5);
        jScrollPane1.setViewportView(txtdetail);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Pages");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Price");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Book Type");

        txtpage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtprice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtbooktype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtbooktype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Borrow", "Read Only" }));

        lblmother.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblmother.setText("Publisher");

        txtpublisher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblfather.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblfather.setText("Author");

        txtauthor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblid, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbid)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtedtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmother)
                            .addComponent(lblfather))
                        .addGap(32, 32, 32)
                        .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtprice)
                        .addComponent(txtpage)
                        .addComponent(txtctgry, 0, 356, Short.MAX_VALUE)
                        .addComponent(txtbooktype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtbid, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addComponent(txtctgry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfather))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmother, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtedtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bookTableDetail.setAutoCreateRowSorter(true);
        bookTableDetail.setBackground(new java.awt.Color(204, 255, 204));
        bookTableDetail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bookTableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Father Name", "Mother Name", "NID", "BirthDate", "Gender", "Address", "Email", "Contact", "Member Type"
            }
        ));
        bookTableDetail.setColumnSelectionAllowed(true);
        bookTableDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bookTableDetail);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbookheadibg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblbookheadibg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupbookActionPerformed
        // TODO add your handling code here:

        String bid = txtbid.getText();
        String bname = txtbname.getText();
        String author = txtauthor.getText();
        String publisher = txtpublisher.getText();
        String edition = txtedtn.getText();
        String bdate = ((JTextField) txtbdate.getDateEditor().getUiComponent()).getText();
        String category = txtctgry.getSelectedItem().toString();
        String detail = txtdetail.getText();
        String page = txtpage.getText();
        String price = txtprice.getText();
        String btype = txtbooktype.getSelectedItem().toString();

        try {
            String updateSql = "UPDATE `addbook` SET `bid`='" + bid + "',`bname`='" + bname + "',`author`='" + author + "',"
                    + "`publish`='" + publisher + "',`edition`='" + edition + "',"
                    + "`bookdate`='" + bdate + "',`category`='" + category + "',`detail`='" + detail + "',"
                    + "`page`='" + page + "',`price`='" + price + "',`booktype`='" + btype + "' WHERE `bid`='" + bid + "'";
            pat = (PreparedStatement) con.prepareStatement(updateSql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane, "Update Successful");
            tablellord();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnupbookActionPerformed

    private void btndltbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndltbookActionPerformed
        // TODO add your handling code here:
        try {
            String deleteSql = "DELETE FROM `addbook` WHERE `bid`='"+txtbid.getText()+"'";
            pat = (PreparedStatement) con.prepareStatement(deleteSql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane, "Delete Successful");
            tablellord();
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btndltbookActionPerformed

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
        // TODO add your handling code here:

        String bid = txtbid.getText();
        String bname = txtbname.getText();
        String author = txtauthor.getText();
        String publisher = txtpublisher.getText();
        String edition = txtedtn.getText();
        String bdate = ((JTextField) txtbdate.getDateEditor().getUiComponent()).getText();
        String category = txtctgry.getSelectedItem().toString();
        String detail = txtdetail.getText();
        String page = txtpage.getText();
        String price = txtprice.getText();
        String btype = txtbooktype.getSelectedItem().toString();

        try {
            String insertSql = "INSERT INTO `addbook`(`bid`, `bname`, `author`,`publish`,`edition`, `bookdate`, "
                    + "`category`, `detail`, `page`, `price`, `booktype`) VALUES "
                    + "('" + bid + "','" + bname + "','" + author + "','" + publisher + "',"
                    + "'" + edition + "','" + bdate + "','" + category + "','" + detail + "','" + page + "',"
                    + "'" + price + "','" + btype + "')";
            pat = (PreparedStatement) con.prepareStatement(insertSql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully Insert");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        clearfield();
        autoId();
        tablellord();

    }//GEN-LAST:event_btnaddbookActionPerformed

    private void tablellord(){
        
        try {
            String sql = "SELECT `bid`, `bname`, `author`,`publish`,`edition`, `bookdate`, `category`, "
                    + "`detail`, `page`, `price`, `booktype` FROM `addbook`";
            pat = (PreparedStatement) con.prepareStatement(sql);
            rst = pat.executeQuery();
            bookTableDetail.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rst));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void autoId()
    {
        try{
            String selectSql = "SELECT `bid` FROM `addbook` ORDER BY bid DESC LIMIT 1";
            pat =(PreparedStatement) con.prepareStatement(selectSql);
            rst = pat.executeQuery();
            if(rst.next())
            {
                String rnno = rst.getString("bid");
                int on = rnno.length();
                String txt = rnno.substring(0, 3);
                String num = rnno.substring(3, on);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String firstText = txt + snum;
                txtbid.setText(firstText);
            }
            
            else{
                
                txtbid.setText("BID10000");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void clearfield()
    {
        
        txtbid.setText("");
        txtbname.setText("");
        txtauthor.setText("");
        txtpublisher.setText("");
        txtedtn.setText("");
        ((JTextField) txtbdate.getDateEditor().getUiComponent()).setText("");
        txtctgry.setSelectedIndex(0);        
        txtdetail.setText("");
        txtpage.setText("");
        txtprice.setText("");
        txtbooktype.setSelectedIndex(0);
        
    }
    

    
    private void txtctgryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtctgryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtctgryActionPerformed

    private void bookTableDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableDetailMouseClicked
        // TODO add your handling code here:

        DefaultTableModel tableModel = (DefaultTableModel) bookTableDetail.getModel();
        int selectRowIndex = bookTableDetail.getSelectedRow();

        txtbid.setText(tableModel.getValueAt(selectRowIndex, 0).toString());
        txtbname.setText(tableModel.getValueAt(selectRowIndex, 1).toString());
        txtauthor.setText(tableModel.getValueAt(selectRowIndex, 2).toString());
        txtpublisher.setText(tableModel.getValueAt(selectRowIndex, 3).toString());
        txtedtn.setText(tableModel.getValueAt(selectRowIndex, 4).toString());
        ((JTextField) txtbdate.getDateEditor().getUiComponent()).setText(tableModel.getValueAt(selectRowIndex, 5).toString());
        txtctgry.setSelectedItem(tableModel.getValueAt(selectRowIndex, 6).toString());
        txtdetail.setText(tableModel.getValueAt(selectRowIndex, 7).toString());
        txtpage.setText(tableModel.getValueAt(selectRowIndex, 8).toString());
        txtprice.setText(tableModel.getValueAt(selectRowIndex, 9).toString());
        txtbooktype.setSelectedItem(tableModel.getValueAt(selectRowIndex, 10).toString());

    }//GEN-LAST:event_bookTableDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTableDetail;
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btndltbook;
    private javax.swing.JButton btnupbook;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lblbookheadibg;
    private javax.swing.JLabel lblbookmhd;
    private javax.swing.JLabel lblfather;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmother;
    private javax.swing.JTextField txtauthor;
    private com.toedter.calendar.JDateChooser txtbdate;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtbname;
    private javax.swing.JComboBox<String> txtbooktype;
    private javax.swing.JComboBox<String> txtctgry;
    private javax.swing.JTextArea txtdetail;
    private javax.swing.JTextField txtedtn;
    private javax.swing.JTextField txtpage;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    // End of variables declaration//GEN-END:variables
}
