/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    Connection con = null;
    public Home() {
        initComponents();
        clock();
        con = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        HomeDesktop = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblLibraryHeading = new javax.swing.JLabel();
        tdate = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        bookissue = new javax.swing.JButton();
        about = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnbook = new javax.swing.JButton();
        txtdate = new javax.swing.JLabel();
        txttime = new javax.swing.JLabel();
        bookreturn = new javax.swing.JButton();
        btnmemberlist = new javax.swing.JButton();
        btnbooklist = new javax.swing.JButton();
        issuehistory = new javax.swing.JButton();
        pendinglist = new javax.swing.JButton();
        backup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1319, 675));
        setPreferredSize(new java.awt.Dimension(1319, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HomeDesktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background1.jpg"))); // NOI18N

        jDesktopPane1.setLayer(HomeDesktop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 1130, 630));

        lblHeader.setBackground(new java.awt.Color(0, 153, 255));
        lblHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1320, 40));

        lblLibraryHeading.setBackground(new java.awt.Color(255, 255, 255));
        lblLibraryHeading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLibraryHeading.setText("Library Management System");
        getContentPane().add(lblLibraryHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 350, 40));

        tdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tdate.setText("Date:");
        getContentPane().add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 70, 40));

        time.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        time.setText("Time:");
        time.setToolTipText("");
        time.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 50, 40));

        bookissue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookissue.setText("Books Issue");
        bookissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookissueActionPerformed(evt);
            }
        });
        getContentPane().add(bookissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 40));

        about.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 150, 40));

        btnMember.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMember.setText(" Memebers");
        btnMember.setToolTipText("");
        btnMember.setActionCommand("Member");
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 50));

        btnbook.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnbook.setText("Books");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        getContentPane().add(btnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 40));

        txtdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtdate.setText("a");
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 140, 40));

        txttime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txttime.setText("a");
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 150, 40));

        bookreturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bookreturn.setText("Books Return");
        bookreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookreturnActionPerformed(evt);
            }
        });
        getContentPane().add(bookreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 40));

        btnmemberlist.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnmemberlist.setText("Member List");
        btnmemberlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnmemberlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        btnbooklist.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnbooklist.setText("Books List");
        btnbooklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbooklistActionPerformed(evt);
            }
        });
        getContentPane().add(btnbooklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, 40));

        issuehistory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        issuehistory.setText("Issues List");
        issuehistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuehistoryActionPerformed(evt);
            }
        });
        getContentPane().add(issuehistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 150, 40));

        pendinglist.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pendinglist.setText("Pending List");
        pendinglist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendinglistActionPerformed(evt);
            }
        });
        getContentPane().add(pendinglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, 40));

        backup.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backup.setText("BackUp");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        getContentPane().add(backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, 40));

        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setText("LogOut");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 150, 40));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 670));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        jLabel5.setBackground(new java.awt.Color(102, 255, 204));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 530, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clock()
    {
        Thread clock = new Thread()
                {
                    public void run()
                    {
                            try {
                                while(true)
                                {
                                    Calendar cal = new GregorianCalendar();
                                    int day = cal.get(Calendar.DAY_OF_MONTH);
                                    int month = cal.get(Calendar.MONTH) + 1;
                                    int year = cal.get(Calendar.YEAR);
                                    
                                    int second = cal.get(Calendar.SECOND);
                                    int minute = cal.get(Calendar.MINUTE);
                                    int hour = cal.get(Calendar.HOUR);
                                    
                                    txtdate.setText(day + "-" + month + "-"+ year);
                                    txttime.setText(hour + ":" + minute + ":" + second);
                                    sleep(100);
                                    
                                } 
                            }catch(Exception e)
                            {
                                    JOptionPane.showMessageDialog(rootPane, e);
                            }
                    }
                };
    clock.start();
    }
            
    
    private void bookissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookissueActionPerformed
        // TODO add your handling code here:   //Borrow
        HomeDesktop.removeAll();
        Borrow borrow = new Borrow();
        HomeDesktop.add(borrow).setVisible(true);
        
    }//GEN-LAST:event_bookissueActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        // TODO add your handling code here: // AddMember
        HomeDesktop.removeAll();
        AddMember addmember = new AddMember();
        HomeDesktop.add(addmember).setVisible(true);
        
    }//GEN-LAST:event_btnMemberActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:  //about 
        
    }//GEN-LAST:event_aboutActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
        // TODO add your handling code here: // Add Book
        HomeDesktop.removeAll();
        AddBook addbook = new AddBook();
        HomeDesktop.add(addbook).setVisible(true);
    }//GEN-LAST:event_btnbookActionPerformed

    private void bookreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookreturnActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Return rtrn = new Return();
        HomeDesktop.add(rtrn).setVisible(true);
    }//GEN-LAST:event_bookreturnActionPerformed

    private void btnmemberlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberlistActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Memberlist memberlist = new Memberlist();
        HomeDesktop.add(memberlist).setVisible(true);
    }//GEN-LAST:event_btnmemberlistActionPerformed

    private void btnbooklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbooklistActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Booklist booklist = new Booklist();
        HomeDesktop.add(booklist).setVisible(true);
    }//GEN-LAST:event_btnbooklistActionPerformed

    private void issuehistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuehistoryActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Issuelist issuhistory = new Issuelist();
        HomeDesktop.add(issuhistory).setVisible(true); 
    }//GEN-LAST:event_issuehistoryActionPerformed

    private void pendinglistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendinglistActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Pendinglist pending_list = new Pendinglist();
        HomeDesktop.add(pending_list).setVisible(true);
    }//GEN-LAST:event_pendinglistActionPerformed

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
        // TODO add your handling code here:
        HomeDesktop.removeAll();
        Backup back_up = new Backup();
        HomeDesktop.add(back_up).setVisible(true);
    }//GEN-LAST:event_backupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeDesktop;
    private javax.swing.JButton about;
    private javax.swing.JButton backup;
    private javax.swing.JButton bookissue;
    private javax.swing.JButton bookreturn;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnbook;
    private javax.swing.JButton btnbooklist;
    private javax.swing.JButton btnmemberlist;
    private javax.swing.JButton issuehistory;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLibraryHeading;
    private javax.swing.JButton login;
    private javax.swing.JButton pendinglist;
    private javax.swing.JLabel tdate;
    private javax.swing.JLabel time;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txttime;
    // End of variables declaration//GEN-END:variables
}
